org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.232
loader_version_range=[1,)

mod_id=solarfluxkeepupgrades
mod_name=Solar Flux Keep Upgrades
mod_license=The MIT License (MIT)
mod_version=1.0.0
mod_group_id=com.christofmeg.solarfluxkeepupgrades

# CurseForgeGradle | Minotaur options
cf_id=1449902
modrinth_id=RrSIqnHR
release_type=release
neoforge_release_versions=1.21.1