
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
forge_supported_versions=1.20-1.20.1

mapping_channel=official
mapping_version=1.20.1

mod_id=solarfluxkeepupgrades
mod_name=Solar Flux Keep Upgrades
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=com.christofmeg.solarfluxkeepupgrades
mod_authors=Christofmeg
mod_description=Prevents accidental voiding of solar panel upgrades.

# CurseForgeGradle | Minotaur options
cf_id=1449902
modrinth_id=RrSIqnHR
release_type=release
forge_release_versions=1.20.1,1.20